# Generated by Django 6.0.7 on 2026-07-18 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('account_type', models.CharField(choices=[('wallet', 'Carteira'), ('checking', 'Conta corrente'), ('savings', 'Poupança'), ('investment', 'Investimento'), ('credit_card', 'Cartão de crédito')], max_length=20, verbose_name='Tipo de conta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo inicial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
